server:
  port: 8080
  context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.5/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://132.232.117.84/dbgirls?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

